pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  name: docker-image-builder
spec:
  restartPolicy: Never
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:latest-jdk21
    workingDir: /home/jenkins/agent
    volumeMounts:
      - name: workspace
        mountPath: /home/jenkins/agent

  - name: buildah
    image: quay.io/containers/buildah:stable
    securityContext:
      privileged: true
    command: ["/bin/sh"]
    args: ["-c", "cat"]
    tty: true
    workingDir: /home/jenkins/agent
    volumeMounts:
      - name: registry-creds
        mountPath: /root/.docker/config.json
        subPath: .dockerconfigjson
      - name: workspace
        mountPath: /home/jenkins/agent

  volumes:
    - name: registry-creds
      secret:
        secretName: registry-creds
    - name: workspace
      emptyDir: {}
"""
        }
    }

    environment {
        IMAGE_NAME = "docker.io/deemack/book-engine"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Determine Tag') {
            steps {
                container('jnlp') {
                    script {
                        env.IMAGE_TAG = sh(
                            script: "git rev-parse --short HEAD",
                            returnStdout: true
                        ).trim()

                        echo "Using image tag: ${env.IMAGE_TAG}"
                    }
                }
            }
        }

        stage('Build & Push Image') {
            steps {
                container('buildah') {
                    sh """
                    echo "Building image ${IMAGE_NAME}:${IMAGE_TAG}"

                    buildah bud -t ${IMAGE_NAME}:${IMAGE_TAG} book-engine
                    buildah tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest

                    buildah push ${IMAGE_NAME}:${IMAGE_TAG}
                    buildah push ${IMAGE_NAME}:latest
                    """
                }
            }
        }
    }
}
